[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alok8663/Pandas/blob/main/Pandas2.ipynb)


# Write CSV File

In [24]:
import pandas as pd
dis={'a':[1,2,3,4,5,6],'s':[6,5,4,3,2,1],'d':[12,3,4,6,5,7]}
d=pd.DataFrame(dis)
print(d)

d.to_csv("Test_new.csv",header=['A','B','C'],index=False)

   a  s   d
0  1  6  12
1  2  5   3
2  3  4   4
3  4  3   6
4  5  2   5
5  6  1   7


# Read CSV File

In [25]:
dataset=pd.read_csv('Test_new.csv',nrows=3,usecols=["A","B"])
dataset

A  B
0  1  6
1  2  5
2  3  4

In [26]:
dataset1=pd.read_csv('Test_new.csv',skiprows=[0])
dataset1

1  6  12
0  2  5   3
1  3  4   4
2  4  3   6
3  5  2   5
4  6  1   7

In [27]:
dataset2=pd.read_csv('Test_new.csv',header=1)
dataset2

1  6  12
0  2  5   3
1  3  4   4
2  4  3   6
3  5  2   5
4  6  1   7

In [28]:
dataset3=pd.read_csv('Test_new.csv',index_col='C')
dataset3

A  B
C       
12  1  6
3   2  5
4   3  4
6   4  3
5   5  2
7   6  1

In [29]:
dataset4=pd.read_csv('Test_new.csv',names=['Col1','Col2','Col3'])
dataset4

Col1 Col2 Col3
0    A    B    C
1    1    6   12
2    2    5    3
3    3    4    4
4    4    3    6
5    5    2    5
6    6    1    7

In [30]:
dataset5=pd.read_csv('Test_new.csv',header=None)
dataset5

0  1   2
0  A  B   C
1  1  6  12
2  2  5   3
3  3  4   4
4  4  3   6
5  5  2   5
6  6  1   7

In [31]:
dataset6=pd.read_csv('Test_new.csv',dtype={"A":"float","B":"f"})
dataset6

A    B   C
0  1.0  6.0  12
1  2.0  5.0   3
2  3.0  4.0   4
3  4.0  3.0   6
4  5.0  2.0   5
5  6.0  1.0   7

# Pandas Functions

In [32]:
dataset7=pd.read_csv('Test_new.csv')

In [33]:
dataset7.index

RangeIndex(start=0, stop=6, step=1)

In [34]:
dataset7.columns

Index(['A', 'B', 'C'], dtype='object')

In [35]:
dataset7.describe()

A         B          C
count  6.000000  6.000000   6.000000
mean   3.500000  3.500000   6.166667
std    1.870829  1.870829   3.188521
min    1.000000  1.000000   3.000000
25%    2.250000  2.250000   4.250000
50%    3.500000  3.500000   5.500000
75%    4.750000  4.750000   6.750000
max    6.000000  6.000000  12.000000

In [36]:
dataset7.head()  # .head() function shows only first 5-rows of the dataset(useful in case of large datasets).

A  B   C
0  1  6  12
1  2  5   3
2  3  4   4
3  4  3   6
4  5  2   5

In [37]:
dataset7.head(2)

A  B   C
0  1  6  12
1  2  5   3

In [38]:
dataset7.tail()  #.tail() function shows last 5-rows of the dataset.

A  B  C
1  2  5  3
2  3  4  4
3  4  3  6
4  5  2  5
5  6  1  7

In [39]:
dataset7.tail(1)

A  B  C
5  6  1  7

In [40]:
dataset7[:2]

A  B   C
0  1  6  12
1  2  5   3

In [41]:
dataset7.index.array

<NumpyExtensionArray>
[0, 1, 2, 3, 4, 5]
Length: 6, dtype: int64

In [42]:
dataset7.to_numpy()

array([[ 1,  6, 12],
       [ 2,  5,  3],
       [ 3,  4,  4],
       [ 4,  3,  6],
       [ 5,  2,  5],
       [ 6,  1,  7]])

In [43]:
import numpy as np
dataset8=pd.read_csv('Test_new.csv')
v=np.asarray(dataset8)
print(v)

[[ 1  6 12]
 [ 2  5  3]
 [ 3  4  4]
 [ 4  3  6]
 [ 5  2  5]
 [ 6  1  7]]


In [44]:
dataset8.sort_index(axis=0,ascending=False)

A  B   C
5  6  1   7
4  5  2   5
3  4  3   6
2  3  4   4
1  2  5   3
0  1  6  12

In [45]:
print(dataset8)

   A  B   C
0  1  6  12
1  2  5   3
2  3  4   4
3  4  3   6
4  5  2   5
5  6  1   7


In [47]:
dataset8.loc[0,"A"]=666
print(dataset8)

     A  B   C
0  666  6  12
1    2  5   3
2    3  4   4
3    4  3   6
4    5  2   5
5    6  1   7


In [49]:
dataset8.loc[[2,3],['B','C']]

B  C
2  4  4
3  3  6

In [50]:
dataset8.loc[:,['B','C']]

B   C
0  6  12
1  5   3
2  4   4
3  3   6
4  2   5
5  1   7

In [53]:
dataset8.loc[:,['B','C']].values

array([[ 6, 12],
       [ 5,  3],
       [ 4,  4],
       [ 3,  6],
       [ 2,  5],
       [ 1,  7]])

In [52]:
dataset8.iloc[:,-1]

0    12
1     3
2     4
3     6
4     5
5     7
Name: C, dtype: int64

In [54]:
dataset8.iloc[:,-1].values

array([12,  3,  4,  6,  5,  7])

In [56]:
dataset8.drop('C',axis=1)

A  B
0  666  6
1    2  5
2    3  4
3    4  3
4    5  2
5    6  1

In [57]:
dataset8.drop(1,axis=0)

A  B   C
0  666  6  12
2    3  4   4
3    4  3   6
4    5  2   5
5    6  1   7